server:
  applicationContextPath: /example-dropwizard/v1
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
      - type: console
        threshold: ALL

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
  password: postgres
  properties:
    charSet: UTF-8
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute

flyway:
  migrationFilesLocation: filesystem:src/main/resources/db.migration

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %logger{0}:%L - %m%n"
      logFormat: "%-5level [%date] %logger: %message \n"